### ISSUE TITLE
Error message during make -> has to be run twice

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/CommonTools#64]
Each time I build histFactory I get this message when calling make (after configuring cmake in a CMS environment):
```
Error: Renaming Framework_dict.cpp_tmp into Framework_dict.cpp!
make[2]: *** [Framework_dict.cpp] Error 1
make[2]: *** Waiting for unfinished jobs....
Error: Renaming TTAnalysis_dict.cpp_tmp into TTAnalysis_dict.cpp!
make[2]: *** [TTAnalysis_dict.cpp] Error 1
make[1]: *** [CMakeFiles/multidraw.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
In the end some stuff is not built (such as createHistoWithMultiDraw.exe). Calling make again there is no error and everything gets built. Is that expected?

**Comment by blinkseb** [comment]
It should happen only when running make with more than one core. I need to
investigate more, but it's because dictionary generation create a 'file'
rule in cmake and they are known to be problematic in multicore (make tried
to generate each dictionary more than once in parallel and one fails)

I know there's way to fix this by adding some dependencies between rules
manually.

You found at leat one workaround. The other is to run make without the -j
option.
Le 21 déc. 2015 13:43, "Sébastien Wertz" <notifications@github.com> a
écrit :

**Comment by swertz** [comment]
Hm, I see! In make you can do something like that: https://github.com/swertz/MEMcpp/blob/master/makefile#L30
No idea for cmake though...

**Comment by blinkseb** [comment]
Also fixed
